### ISSUE TITLE
Deprecated methode in Selenium 

### ISSUE THREAD

**Issue by anas0bito** [0x00Nu11/egyCrawler#2]
Selenium just removed
`driver.find_element_by_xpath('path')` in 4.3.x
use
`driver.find_element("xpath", 'path') `
and ty king

**Comment by 0x00Nu11** [comment]
thank you, I'll replace all instances of `find_element_by_xpath()` soon.
I think a lot of stuff is broken, not fixing it now as I'm busy with college, but I'm planning on re-writing the whole thing and getting rid of Selenium as a whole, since finding the source of the m3u8 streams and downloading through ffmpeg would be lighter and faster.

**Comment by anas0bito** [comment]
good luck bro
whats the library u will use then
and how long have you learn python

**Comment by 0x00Nu11** [comment]
fixed, along with other stuff that was causing some errors.

> whats the library u will use then
> and how long have you learn python

ffmpeg, asyncio, bs4, and requests should be enough
and I've been learning python for a little over a year now, on and off
